### ISSUE TITLE
one click option

### ISSUE THREAD

**Issue by gaelforget** [gaelforget/gradientsWG1#1]
Hi @mdashkezari 

What do you think about merging the csvfiles branch to master?

This would gives folks a one-click option to get all of gradients & allow them to e.g. easily add columns of collocated variables without having to wait / decide on ingestion into cmap at first & use version controls, DOIs etc

Several folks seem to really want an option like that as you will remember. It's your call though (I just talked with @gingerarmbrust about this) and I am totally fine with deleting the branch from GitHub (I have what I need for myself, just trying to help out others here...) if you want to avoid such repost of the CSVs

Please let me know asap (until then I will leave this up so you can view the branch...)

Thanks in advance

ps. I would use slack but I feel I am getting nowhere with that...

**Comment by mdashkezari** [comment]
Hi Gael, 
Sure, that's fine with me.
I think you've also shared the notebook to retrieve these files. So people should be able to reproduce your work if any of these datasets is updated.

**Comment by gaelforget** [comment]
> Hi Gael,
> Sure, that's fine with me.

Great! Thanks Mohammad. Will merge and release / DOI

> I think you've also shared the notebook to retrieve these files. So people should be able to reproduce your work if any of these datasets is updated.

Indeed -- that's `gaelforget/MarineEcosystemNotebooks (v0.1.5): improved DarwinModelOutput & GradientsCruiseData notebooks. http://doi.org/10.5281/zenodo.3766311
